@startuml

title UC009(担当者アカウント登録機能)のシーケンス図
actor "担当者" as user
participant "Controller" as controller
participant "Employee\nService" as service
participant "FormEmployee" as form
participant "Employee\nConverter" as helper
participant "Employee\nRepository" as repository
database "db" as db
 == 入力 ==
user -> controller++:form()
controller -> service++:getEmployeeList()
service -> repository++:selectAllEmployee()
repository -> db++:SQL(SELECT EMPLOYEES)
db -> repository--:List<Employee>
repository -> service--:List<Employee>
service -> controller--:List<Employee>
controller -> controller:Modelにセット\n(プルダウン用)
controller -> user--:入力画面
user -> user:アカウント入力 
 == 確認 ==
user -> controller++:confirm()
controller -> form++:アカウント情報セット
form -> controller--:FormEmployee
controller -> controller:バリデート
controller -> user--:確認画面
 == 完了 ==
user -> controller++:execute()
controller -> service++:addAccount(FormEmployee)
service -> helper++:convertToEntity\n(FormEmployee)
helper -> service--:Employee
service -> repository++:insert(Employee)
repository -> db++:SQL(INSERT)
db -> repository--:void
repository -> service--:void
service -> controller--:void
controller -> user--:リダイレクト
user -> controller++:complete()
controller -> controller:セッション破棄
controller -> user--:完了画面
@enduml