@startuml
title 商品カテゴリ登録
actor user
participant RegisterCategoryProductController as Controller
participant FormProduct as Form
participant ProductCategoryService as Service
participant ProductHelper as Helper
participant ProductRepository as Repository
database DB


user -> Controller++:input()
user <-- Controller--:商品カテゴリ登録入力画面
==入力==
user -> Controller++:confirm()
Controller -> Form++:商品カテゴリ情報セット\n new FormProduct()
Controller <-- Form--:FormProduct
Controller -> Controller:バリデート
user <-- Controller--:商品カテゴリ登録確認画面
==確認==
user -> Controller++:execute()
Controller -> Service++:addCategory(formCategory:FormCategory)
Service -> Repository++:addCategory(ProductCategory)
Repository -> DB++:insert(ProductCategory)
Repository <-- DB--:void
Service <-- Repository--:void
Controller <-- Service--:void
user <-- Controller--:リダイレクト
user --> Controller++:complete()
Controller -> Controller:セッション破棄
user <-- Controller--:商品カテゴリ登録完了画面
==完了==
@enduml