@startuml
title 商品削除
actor user
participant ProductController as Controller
participant FormProduct as Form
participant ProductService as Service
participant ProductHelper as Helper
participant ProductRepository as Repository
database DB


user -> Controller++:confirm()
user <-- Controller--:商品削除確認画面
==確認==
user -> Controller++:execute()
Controller -> Service++:()
Service -> Repository++:productDelete(Integer)
Repository -> DB++:delete(Integer)
Repository <-- DB--:void
Service <-- Repository--:void
Controller <-- Service--:void
user <-- Controller--:リダイレクト
user --> Controller++:complete()
Controller -> Controller:セッション破棄
user <-- Controller--:商品削除完了画面
==完了==
@enduml