@startuml

title カテゴリ別商品検索のシーケンス図
actor "担当者" as user
participant "SearchProductController" as controller
participant "ProductCategory\nService" as service
participant "Product\nService" as service1
participant "Product\nConverter" as helper
participant "ProductCategory\nRepository" as repository1
participant "Product\nRepository" as repository2
database "db" as db
==表示==
user -> controller++:input()
controller -> service1++:selectProductByPage(pageable: Pageable)
service1 -> repository2++:selectByPage(pageable:Pageable)
repository2 -> db++:SQL(SELECT(count)
db -> repository2--:List<Product>
repository2 -> service1--:List<Product>
service1 -> controller--:page<Product>

controller -> service++:selectAll()
service -> repository1++:selectAll()
repository1 -> db++:SQL(SELECT)
db -> repository1--:List<ProductCategory>
repository1 -> service--:List<ProductCategory>
service -> controller--:List<ProductCategory>
controller -> controller:Modelにセット\n(プルダウン用)
controller -> user--:カテゴリ別商品検索入力画面

== 検索 ==
user -> controller++:execute()
controller -> service++:getProductListByCategoryId(Integer)
service -> repository2++:+selectByCategoryId(Integer)
repository2 -> db++:select
db -> repository2--:List<Product>
repository2 -> service--:List<Product>
service -> helper++:convertToEntity(FormProduct)
service <- helper--:Product
service -> controller--:List<FormProduct>
controller -> controller:Modelにセット
controller -> user--:カテゴリ別商品検索完了画面


@enduml