@startuml
title 担当者アカウントログイン
actor user
participant "Account\nLoginController" as controller
participant "SecurityConfig" as security
participant "AccountUser\nDetailsService" as service
participant "Employee\nRepository" as repository
participant "Account\nUserDetails" as details
database DB as db

user -> controller++:login()
controller -> user--:ログイン画面
user -> security++:/auth POST(username, password)
security -> service++:loadUserByUsername\n(username)
service -> repository++:selectByUsername\n(username)
repository -> db++:SELECT文
db --> repository--:Account
repository --> service--:Account
service -> details++:new
details --> service--:AccountUserDetails
service -> security--:AccountUserDetails
security -> security:認証
security -> security:セッションに格納
security --> user--:メニューへリダイレクト
user -> controller++:menu()
controller -> user--:メニュー画面

@enduml