@startuml
title 商品登録
actor user
participant RegisterProductController as Controller
participant FormProduct as Form
participant ProductCategoryService as Service1
participant ProductService as Service
participant ProductHelper as Helper
participant ProductCategoryRepository as Repository1
participant ProductRepository as Repository
database DB

==入力==
user -> Controller++:input()
Controller -> Service1++:selectAll()
Service1 -> Repository1++:selectAll()
Repository1 -> DB++:SQL(select)
DB -> Repository1 --:List<FormCategory>
Repository1 -> Service1--:List<FormCategory>
Service1 -> Controller--:List<FormCategory>
user <-- Controller--:商品登録入力画面
==確認==
user -> Controller++:confirm()
Controller -> Form++:商品情報セット
Controller <-- Form--:FormProduct
Controller -> Controller:バリデート
user <-- Controller--:商品登録確認画面
==完了==
user -> Controller++:execute()
Controller -> Service++:addProduct(formProduct:FormProduct)
Service -> Helper++:convertToEntity(FormProduct)
Service <-- Helper--:Product
Service -> Repository++:addProduct(Product)
Repository -> DB++:insert(Product)
Repository <-- DB--:void
Service <-- Repository--:void
Controller <-- Service--:void
user <-- Controller--:リダイレクト
user --> Controller++:complete()
Controller -> Controller:セッション破棄
user <-- Controller--:商品登録完了画面

@enduml