@startuml
title 商品削除
actor user
participant DeleteProductController as Controller

participant ProductService as Service
participant ProductRepository as Repository
database DB

==確認==
user -> Controller++:confirm()
user <-- Controller--:商品削除確認画面
==完了==
user -> Controller++:execute()
Controller -> Service++:deleteProduct(Integer:Id)
Service -> Repository++:productDelete(Integer)
Repository -> DB++:updateDeleteFlag(Integer)
Repository <-- DB--:void
Service <-- Repository--:void
Controller <-- Service--:void
user <-- Controller--:リダイレクト
user --> Controller++:complete()
Controller -> Controller:セッション破棄
user <-- Controller--:商品削除完了画面

@enduml