package config{
    class Config{
        + passwordEncoder(): PasswordEncoder
  
    }


    class WebMvcConfig implements WebMvcConfigurer {
        + addArgumentResolvers(resolvers: List<HandlerMethodArgumentResolver>): void
    }

  
}