@startuml
title controller
hide empty members
left to right direction

package controller{
    class CustomerLoginController{
        +login():String
        +top():String
        +logout():String
    }
    class PurchaseController{
        +input():String
        +confirm():String
        +execute():String
        +complete():String
    }
    class PurchaseHistoryController{
        +history():String
        +detailHistory():String
    }
    class SearchProductController{
        +seachProductByCategory():String
        +execute():String
        +productDetail():String
    }
    class CustomerAccountController{
        +input():String
        +confirm():String
        +execute():String
        +complete():String
    }
}

@enduml