@startuml
title form層のクラス図
hide empty members
left to right direction

package form{

    class CustomerForm{
        -customerName: String
        -customerNameKana: String
        -customerAddress1: String
        -customerAddress2: String
        -customerPhoneNumber: String
        -customerMailAdress:String
        -customerUserName: String
        -customerPassword: String
        -customerRegisterDate: String
    }

    class OrderForm{
        -orderId: Integer
        -orderDate: String
        -amountTotal: Integer
        -count: Integer
        -orderStatus: String
        -payMethod: String
        -customerName: String
    }

    class ProductForm{
        -prodId: Integer
        -prodName: String
        -price: Integer
        -file: MultipartFile
        -categoryId: Integer
        -quantity: Integer
        -stockId: Integer
    }
    
    class CategoryForm{
        -categoryId: Integer
        -categoryName: String
    }
	

    class CustomerRegisterFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
    
    class OrderFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
    
    class PruductFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }

}
@enduml



