@startuml
title form層のクラス図
hide empty members
left to right direction

package form{

    class CustomerForm{
        -customerName: String
        -customerNameKana: String
        -customerAddress1: String
        -customerAddress2: String
        -customerPhoneNumber: String
        -customerMailAdress:String
        -customerUsername: String
        -customerPassword: String
        -customerRegisterDate: ZonedDateTime
    }

    class OrderForm{
        -orderId: Integer
        -orderDate: String
        -amountTotal: Integer
        -orderStatusId: Integer
        -paymentMethodId: Integer
        -customerId: Integer
    }

    class OrderDetailForm{
      -orderDetailId:Integer
      -orderId:Integer
      -productId:Integer
      -count:Integer
      -customerId:Integer
      -stock:Integer
    }

    class ProductForm{
        -prodId: Integer
        -prodName: String
        -price: Integer
        -file: MultipartFile
        -categoryId: Integer
        -quantity: Integer
        -stockId: Integer
    }
    
    class CategoryForm{
        -categoryId: Integer
        -categoryName: String
    }
	

    class CustomerRegisterFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
    
    class OrderFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
    
    class PruductFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }

}
@enduml



