@startuml
title helper層のクラス図
hide empty members
left to right direction

package helper{
    class CustomerConverter{
        +convertToEntity(formCustomerRegister:CustomerRegisterForm):Customer
    }

    class OrderConverter{
        +convertToEntity(formOrder:OrderForm):Order
    }

    class ProductConverter{
        +convertToEntity(productform:ProductForm):Product
    }

}
@enduml