@startuml
title repository層のクラス図
hide empty members
left to right direction

package repogitory{
class CustomerRepository{
        +insert(customer:Customer):void
        +selectByMailAddress(mail:String):Customer
        +selectAll():List<Customer>
    }

    class OrderRepository{
        +insert(order:Order):void
        +selectByPage(pageable:Pageable,date:LocalDateTime,customerId:Integer):List<Order>
        +selectAllPaymentMethod():List<PaymentMethod>
        +insertOrderDetail(orderDetail:OrderDetail):void
        +insertOrderStatus(status:String):void
    }

    class ProductRepository{
        +selectByPage(pageable:Pageable):List<Product>
    }

    class ProductCategoryRepository{
        +selectAll():List<ProductCategory>
    }

    class OrderDetailRepository{
        +insert(OrderDetail):void
    }
    
    class StockRepository{
        +selectByProductId(productId):ProductStock
        +updateStock(count:Integer, productStockId):void
    }

    class OrderStatusRepository{
        +selectAll():List<OrderStatus>
    }
}
@enduml