@startuml
title service
hide empty members
left to right direction

package service{
    class CustomerService{
    	+selectAll():List<Customer>
		+getCustomerByMailAddress(address:String):Customer
		+registerCustomer(customer:CustomerForm):void
    }
    
    class OrderService{
		+registerOrder(OrderForm,List<OrderDetailForm>):void
		+deleteOrder():void
	    +updateStatus(OrderForm):void
	    +getOrderStatusList():List<orderStatus>
	    +getOrderList():List<Order>
	    +getStockByProductId(productId:Integer):ProductStock
	    +getStockByOrderDetailForm(orderDetailForm:OrderDetailForm):ProductStock
	    +getPaymentMethodList():List<PaymentMethod>
	    +selectPurchaseHistoryByPage(pageable:Pageable,date:LocalDateTime,customerId:Integer):page<Order>
	   }
    
    class ProductService{
		+selectProductByPage(pageable: Pageable):page<Product>
		+updateProductStock(stock:ProductStock):void
    }

    class ProductCategoryService{
		+selectAll():List<CategoryForm>
    }
}