@startuml
title 全体クラス図
hide empty members
left to right direction

package entity{
    class Customer{
    }

    class Order{
    }

    class OrderDetail{
    }

    class OrderStatus{
    }
    
    class PayMethod{
    }

    class Product{
    }

    class ProdCategory{
    }

    class ProdStock{
    }

    class Employee{
    }

    class Department{
    }

    class EmpAccount{
    }
}

Customer <--> Order
Order --> OrderStatus
Order --> OrderDetail
Order --> PayMethod
Product --> ProdStock
Product --> ProdCategory
Employee --> EmpAccount
Employee --> Department

package form{
    
    class CustomerForm{
    }

    class OrderForm{
    }

    class ProductForm{
    }

    class EmployeeForm{
    }
    
    class EmpAccountForm{
    }
    
    class CustomerFormValidator{
    }
    
    class OrderFormValidator{
    }
    
    class PruductFormValidator{
    }
    
    class EmployeeFormValidator{
    }
}

package helper{
    class CustomerConverter{
    }

    class OrderConverter{
    }

    class ProductConverter{
    }

    class EmployeeConverter{
    }
    
    class ImageUploadHelper{
    }
}
CustomerConverter --> Customer
CustomerConverter --> CustomerForm
OrderConverter --> Order
OrderConverter --> OrderForm
ProductConverter --> Product
ProductConverter --> ProductForm
EmployeeConverter --> EmpAccount
EmployeeConverter --> EmpAccountForm

package repository{
    class CustomerRepository{
    }

    class OrderRepository{
    }

    class ProductRepository{
    }

    class EmployeeRepository{
    }

    class ProductCategoryRepository{
    }

    class OrderDetailRepository{
    }
}

package service{
    class CustomerService{
    }
    
    class OrderService{
    }
    
    class ProductService{
    }

    class EmployeeService{
    }
    
    class ProductCategoryService{
    }
}

CustomerService --> CustomerConverter
OrderService --> OrderConverter
ProductService --> ProductConverter
ProductService --> ImageUploadHelper
EmployeeService --> EmployeeConverter

CustomerService --> CustomerRepository
OrderService --> OrderRepository
OrderService --> OrderDetailRepository
ProductService --> ProductRepository
EmployeeService --> EmployeeRepository
ProductCategoryService --> ProductCategoryRepository

CustomerRepository --> Customer
OrderRepository --> Order
OrderDetailRepository --> OrderDetail
ProductRepository --> Product
EmployeeRepository --> Employee
ProductCategoryRepository --> ProdCategory


package controller{
    class AddAccountContoroller{
    }
    class RegisterProductContoroller{
    }
    class SearchProductContoroller{
    }
    class UpdateProductContoroller{
    }
    class DeleteProductContoroller{
    }
    class RegisterProductCategoryContoroller{
    }
    class AccountLoginContoroller{
    }
    class  AccountLogoutContoroller{
    }
}
AddAccountContoroller --> EmployeeService
RegisterProductContoroller --> ProductService
SearchProductContoroller --> ProductService
UpdateProductContoroller --> ProductService
DeleteProductContoroller --> ProductService
RegisterProductCategoryContoroller --> ProductService
AccountLoginContoroller --> EmployeeService

package aop{
   class LoggingAroundAdvice {
   }
}

package config{
    class Config{
    }
    class WebMvcConfig implements WebMvcConfigurer {
    }
}

package security{

		class securityConfig{
			+ webSecurityCustomizer():WebSecurityCustomizer
			+ securityFilterChain(HttpSecurity http):SecurityFilterChain
		}
		class AccountUserDetailsService{
			loadUserByUsername(String):UserDetails
			getAuthorities(String):Collection<GrantedAuthority>
		}
		class AccountUserDetails{
			+getAuthorities():Collection<? extends GrantedAuthority>
			+getPassword():String
			+getUsername():String
			+isAccountNonExpired():boolean
			+isAccountNonLocked():boolean
			+isCredentialsNonExpired():boolean
			+isEnabled():boolean
		}
	
}
@enduml




