@startuml
title 全体クラス図
hide empty members
left to right direction

package entity{
    class Customer{
    }

    class Order{
    }

    class OrderDetail{
    }

    class OrderStatus{
    }

    class Product{
    }

    class ProdCategory{
    }

    class ProdStock{
    }

    class Employee{
    }

    class Department{
    }

    class EmpAccount{
    }
}

Customer <--> Order
Order --> OrderStatus
Order --> OrderDetail
Order --> Product
Product --> ProdStock
Product --> ProdCategory
Employee --> EmpAccount
Employee --> Department

package form{
    class FormCustomer{
    }

    class FormOrder{
    }

    class FormProduct{
    }

    class FormEmployee{
    }
    
    class FomrCustomerValidator{
    }
    
    class FomrOrderValidator{
    }
    
    class FomrPruductValidator{
    }
    
    class FomrEmployeeValidator{
    }
}

package helper{
    class CustomerConverter{
    }

    class OrderConverter{
    }

    class ProductConverter{
    }

    class EmployeeConverter{
    }
}
CustomerConverter --> Customer
CustomerConverter --> FormCustomer
OrderConverter --> Order
OrderConverter --> FormOrder
ProductConverter --> Product
ProductConverter --> FormProduct
EmployeeConverter --> Employee
EmployeeConverter --> FormEmployee

package repository{
    class CustomerRepository{
    }

    class OrderRepository{
    }

    class ProductRepository{
    }

    class EmployeeRepository{
    }

    class ProductCategoryRepository{
    }

    class OrderDetailRepository{
    }
}

package service{
    class CustomerService{
    }
    
    class OrderService{
    }
    
    class ProductService{
    }

    class EmployeeService{
    }
    
    class ProductCategoryService{
    }
}

package controller{
    class ManagerAccountContoroller{
    }
    class NewItemRegistContoroller{
    }
    class ItemSearchContoroller{
    }
    class ItemSearchContoroller{
    }
    class ItemRetouchContoroller{
    }
    class ItemDeleteContoroller{
    }
    class ItemCategoryRegistContoroller{
    }
    class ManagerAccountLoginContoroller{
    }
    class ManagerAccountLogoutContoroller{
    }
}

package aop{
   class LoggingAroundAdvice {
   }
}

package config{
    class Config{
    }

CustomerService --> CustomerConverter
OrderService --> OrderConverter
ProductService --> ProductConverter
EmployeeService --> EmployeeConverter

CustomerService --> CustomerRepository
OrderService --> OrderRepository
ProductService --> ProductRepository
EmployeeService --> EmployeeRepository
ProductCategoryService --> ProductCategoryRepository

CustomerRepository --> Customer
OrderRepository --> Order
ProductRepository --> Product
EmployeeRepository --> Employee
ProductCategoryRepository --> ProdCategory

@enduml




