package aop{
   class LoggingAroundAdvice {
        + aroundAdvice(joinPoint: ProceedingJoinPoint): Object
    }

    class TransactionManagementAspect {
        - transactionManager: PlatformTransactionManager
        + aroundAdvice(joinPoint: ProceedingJoinPoint, transactional: Transactional): Object
    }

    class SecurityAspect {
        + beforeAdvice(): void
        - checkUserAccess(): boolean
    }


 
}