package controller{
    class AddAccountController{
        -FormEmployee: formEmployee
        + input():String
        + confirm():String
        + execute():String
    	+ complete():String
        
    }
    class RegisterProductController{
    	- FormProduct:formProduct
        + input():String
        + confirm():String
        + execute():String
    	+ complete():String
    }
    class SearchProductController{
    	- FormOrder : formOrder
    	+ searchList():String
    	+ list():String
      
        
    }
    class UpdateProductController{
        - FormOrder : formOrder
     	+ input():String
        + confirm():String
        + execute():String
    	+ complete():String
        
    }
    class DeleteProductController{
    	- FormOrder : formOrder
        + confirm():String
        + execute():String
    	+ complete():String
    }
    class RegisterProductCategoryController{
        - FormOrder : formOrder
        + input():String
        + confirm():String
        + execute():String
    	+ complete():String
    }
    class AccountLoginController{
        -FormEmployee: formEmployee
        + login():String
        + menu():String
        + logout():String
    }
    class MenuController{
        + menu():String
    
}

 

}