package controller{
    class AddAccountController{
        -FormEmployee: formEmployee
        + empInput(): String
        + empConfirm(): String
        + empExecute(): String
        + empComplete(): String
        
    }
    class ProductRegistController{
    	- FormProduct:formProduct
        + productInput(): String
        + productConfirm(): String
        + productExecute(): String
        + productComplete(): String
    }
    class ProductSearchController{
    	- FormOrder : formOrder
    	+ productSearchList():String
    	
      
        
    }
    class ProductUpdateController{
        - FormOrder : formOrder
        + productUpdateInput():String
        + productUpdateConfirm():String
        + productUpdateExecute():String
    	+ productUpdateComplete():String
        
    }
    class ProductDeleteController{
    	- FormOrder : formOrder
        + productDeleteConfirm():String
        + productDeleteExecute():String
    	+ productDeleteComplete():String
    }
    class ProductCategoryRegistController{
        - FormOrder : formOrder
        + productRegistInput():String
        + productRegistConfirm():String
        + productRegistExecute():String
    	+ productRegistComplete():String
    }
    class ManagerAccountLoginController{
        -FormEmployee: formEmployee
        + managerAccountLogin():String
        + menu():String
    }
    class ManagerAccountLogoutController{
        + managerAccountLogout():String
        + managerAccountLogin():String
        
    }
}