@startuml
title entity層のクラス図
hide empty members
left to right direction

package entity{
    class Customer{
        -customerId: Integer
        -customerName: String
        -customerNameKana: String
        -customerAddress1: String
        -customerAddress2: String
        -customerPhoneNumber: String
        -customerUserName: String
        -customerPassword: String
        -customerRegisterDate: String
        -orderList: List<Order>
    }

    class Order{
        -orderId: Integer
        -orderDate: String
        -amountTotal: Integer
        -orderDetail: OrderDetail
        -orderStatus: OrderStatus
        -payMethod: PayMethod
        -customer: Customer
    }

    class OrderDetail{
        -orderDetailId: Integer
        -count: Integer
        -product: Product
        -customer: Customer
    }

    class OrderStatus{
        orderStatusId: Integer
        orderStatusName: String
    }

    class Product{
        -prodId: Integer
        -prodName: String
        -price: Integer
        -imageUrl: String
        -prodCategory: ProdCategory
        -prodStock: ProdStock
    }

    class ProdCategory{
        -prodCategoryId: Integer
        -prodCategoryName: String
        -prodList: List<Product>
    }

    class ProdStock{
        -prodStockId: Integer
        -quantity: Integer
    }

    class Employee{
        -empId: Integer
        -empName: String
        -empNameKana: String
        -department: Department
        -empAccount: EmpAccount
    }

    class Department{
        -deptId: Integer
        -deptName: String
    }

    class EmpAccount{
        -empAccountId: Integer
        -empAccountName: String
        -password: String
    }
}

Customer <--> Order
Order --> OrderStatus
Order --> OrderDetail
Order --> Product
Product --> ProdStock
Product --> ProdCategory
Employee --> EmpAccount
Employee --> Department
@enduml