@startuml
title form層のクラス図
hide empty members
left to right direction

package form{
	class CustomerLoginForm{
		-customerMailAdress: String
		-customerPassword: String
	}

    class CustomerRegisterForm{
        -customerName: String
        -customerNameKana: String
        -customerAddress1: String
        -customerAddress2: String
        -customerPhoneNumber: String
        -customerMailAdress:String
        -customerUserName: String
        -customerPassword: String
        -customerRegisterDate: String
    }

    class OrderForm{
        -orderId: Integer
        -orderDate: String
        -amountTotal: Integer
        -count: Integer
        -orderStatus: String
        -payMethod: String
        -customerName: String
    }

    class ProductForm{
        -prodId: Integer
        -prodName: String
        -price: Integer
        -imageUrl: String
        -categoryName: String
        -quantity: Integer
    }
    
    class CategoryForm{
        -categoryId: Integer
        -categoryName: String
    }
	
	class EmployeeLoginForm{
		-empAccountName: String
        -empAccountPassword: String
	}
	
	class EmpAccountForm{
		-empId: Integer
		-empName: String
		-empAccountName: String
        -empAccountPassword: String
	}
    
    class CustomerLoginValidatorForm{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }

    class CustomerRegisterValidatorForm{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
    
    class OrderValidatorForm{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
    
    class PruductFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
    
    class EmployeeLoginFormValidator{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }

    class EmployeeRegisterFormValidatorForm{
		+support(clazz:class<?>):boolean
		+validator(target:Object,errors:Errors):void
    }
}
@enduml



