@startuml
title form層のクラス図
hide empty members
left to right direction

package form{
    class FormCustomer{
        -customerId: Integer
        -customerName: String
        -customerNameKana String
        -customerAddress1: String
        -customerAddress2: String
        -customerPhoneNumber: String
        -customerUserName: String
        -customerPassword: String
        -customerRegisterDate: String
        -orderList: List<Order>
    }

    class FormOrder{
        -orderId: Integer
        -orderDate: String
        -amountTotal: Integer
        -count: Integer
        -orderStatus: String
        -payMethod: String
        -customerName: String
    }

    class FormProduct{
        -prodId: Integer
        -prodName: String
        -price: Integer
        -imageUrl: String
        -categoryName: String
        -quantity: Integer
    }

    class FormEmployee{
        -empId: Integer
        -empName: String
        -empNameKana: String
        -departmentName: String
        -empAccountId: String
        -empAccountPassword: String
    }
}
@enduml