@startuml
title helper層のクラス図
hide empty members
left to right direction

package helper{
    class CustomerConverter{
        +convertFormCustomerRegisterToCustomer(formCustomerRegister:CustomerRegisterForm):Customer
    }

    class OrderConverter{
        +convertToEntity(formOrder:OrderForm):Order
    }

    class ProductConverter{
        +convertToEntity(formProduct:ProductForm):Product
        +convertFormCategoryToEntity(formCategory:CategoryForm):ProdCategory
    }

    class EmployeeConverter{
        +convertFormEmpAccountToEmployee(EmpAccountform:EmpAccountForm):EmpAccount
    }
    
    class ImageUploadHelper{
    	+uploadFile(filename:String,imageByte:byte[]):String
    }
}
@enduml