@startuml
title helper層のクラス図
hide empty members
left to right direction

package helper{
    class CustomerConverter{
        +convertFormCustomerRegisterToCustomer(formCustomerRegister:FormCustomerRegister):Customer
    }

    class OrderConverter{
        +convertToEntity(formOrder:FormOrder):Order
    }

    class ProductConverter{
        +convertToEntity(formProduct:FormProduct):Product
        +convertFormCategoryToEntity(formCategory:FormCategory):ProdCategory
    }

    class EmployeeConverter{
        +convertFormEmployeeRegisterToEmployee(formEmployeeRegister:FormEmployeeRegister):Employee
    }
    
    class ImageUploadHelper{
    	+uploadFile(filename:String,imageByte:byte[]):String
    }
}
@enduml