@startuml
title helper層のクラス図
hide empty members
left to right direction

package helper{
    class CustomerConverter{
        +convertToForm():FormCustomer
        +convertToEntity():Customer
    }

    class OrderConverter{
        +convertToForm():FormOrder
        +convertToEntity():Order
    }

    class ProductConverter{
        +convertToForm():FormProduct
        +convertToEntity():Product
    }

    class EmployeeConverter{
        +convertToForm():FormEmployee
        +convertToEntity():Employee
    }
}
@enduml