@startuml
title repository層のクラス図
hide empty members
left to right direction

package repository{
    class CustmerRepository{
        +insert(customer:Customer):void
        +selectByIdAndPassword(id:Integer,password:String):Customer
    }

    class OrderRepository{
        +insert(order:Order):void
        +delete(orderId:Integer):void
        +update(order:Order):void
        +selectByDateOrUserName(date:String,uerName:String)
    }

    class ProductRepository{
        +insert(product:Product):void
        +delete(productId:Integer):void
        +update(product:Product):void
        +selectByCategoryId(categoryId:Integer):Product
    }

    class EmployeeRepository{
        +insert(emp:EmployeeAccount):void
        +selectByIdAndPassword(id:Integer,password:String):Employee
        +selectAllEmployee():List<Employee>
    }

    class ProductCategoryRepository{
        +insert(prodCategory:ProdCactegory):void
        +selectAll():List<FormCategory>
    }

    class OrderDetailRepository{
        +update(orderId:Integer, orderDetailStatus:String):void
    }
}
@enduml