@startuml
title サービス層のクラス図
package service{
	class CustomerService implements SomeService{
		+ addCustomer(formCustomer:FormCustomer):void
		+ customerLogin(mailAddress:String, password:String):boolean
	}
	
	class OrderService implements SomeService{
		+ buyProduct(productId:Integer,numberId:Integer):void
		+ cancelOrder(orderId:Integer):void
		+ getOrderList(customerId:Integer):List<FormOrder>
		+ getOrderList(orderDate:String,customerId:Integer):List<FormOrder>
		+ orderStatusUpdate(orderStatusId:Integer):void
	}
	
	class ProductService implements SomeService{
		+ addProduct(formProduct:FormProduct):void
		+ getProductListByCategoryId(categoryId:Integer):List<FormProduct>
		+ getProductByProductId(productId:Integer)Product
		+ productUpdate(formProduct:FormProduct):void
		+ deleteProduct(productId:Integer):void
	}


	class EmployeeSerimplementsvice implements SomeService{
		+ addAccount(formEmployeeAccount:FormEmployeeAccount):void
		+ employeeLogin(name:String,password:String):boolean
		+ getEmployeeList():List<FormEmployee>
	}
	
	class ProductCategoryService implements SomeService{
		+ addCategory(formCartegory:FormCategory):void
		+ selectAll():List<FormCategory>
	}	
}



@enduml