@startuml
title サービス層のクラス図
package service{
	class CustomerService{
		+ addCustomer(formCustomer:FormCustomer):void
		+ customerLogin(mailAddress:String, password:String):boolean
	}
	
	class OrderService{
		+ buyProduct(productId:int,number:id):void
		+ cancelOrder(orderId:int):void
		+ getOrderList(customerId:int):List<FormOrder>
		+ getOrderList(orderDate:String,customerId:int):List<FormOrder>
		+ OrderStatusUpdate(orderStatusId:int):void
	}
	
	class ProductService{
		+ addProduct(formProduct:FormProduct):void
		+ getProductListByCategoryId(categoryId:int):List<FormProduct>
		+ productUpdate(formProduct:FormProduct):void
		+ deleteProduct(productId:int):void
	}


	class EmployeeService{
		+ addAccount(Employee:FormEmployee):void
		+ employeeLogin(name:String,password:String):boolean
		+ getEmployeeList():List<FormEmployee>
	}
	
	class ProductCategoryService{
		+ addCategory(formCartegory:FormCategory):void
		+ selectAll():List<FormCategory>
	}	
}
@enduml