@startuml
title サービス層のクラス図
package service{
	package front{
		class CustmerService{
			+ addCustomer(formCustomer:FormCustomer):void
		}
		
		class CustomerLoginService{
			+ customerLogin(mailAddress:String, password:String):boolean
		}
		
		class CustomerOrderService{
			+ buyProduct(productId:int,number:id):void
			+ cancelOrder(orderId:int):void
			+ getOrderList(customerId:int):List<FormOrder>
		}
		
		class GetProductListByCategoryService{
			+ getProductListByCategory():List<FormProduct>
		}
	}
	package back{
		class EmployeeService{

		}
		
		class EmployeeLoginService{
	
		}
		
		class EmployeeOrderService{
	
		}
		
		class ProductService{
	
		}
		
		class ProductCategoryService{
	
		}
	}
	
	
}
@enduml