
@startuml

title カテゴリ別商品検索のシーケンス図
actor "担当者" as user
participant "SearchProductController" as controller
participant "ProductCategory\nService" as service
participant "Product\nService" as service1
participant "ProductCategory\nRepository" as repository1
participant "Product\nRepository" as repository2
database "db" as db
==表示==
user -> controller++:input()
controller -> service1++:selectProductByPage\n(pageable: Pageable,categoryId:Integer)
service1 -> repository2++:selectByPage(pageable:Pageable,categoryId:Integer)
repository2 -> db++:SQL(SELECT(count))
db -> repository2--:List<Product>
repository2 -> service1--:List<Product>
service1 -> controller--:page<Product>

controller -> service++:selectAll()
service -> repository1++:selectAll()
repository1 -> db++:SQL(SELECT)
db -> repository1--:List<ProductCategory>
repository1 -> service--:List<ProductCategory>
service -> controller--:List<ProductCategory>
controller -> controller:Modelにセット\n(プルダウン用)
controller -> user--:カテゴリ別商品検索画面



@enduml