@startuml

title 購入履歴検索のシーケンス図
actor "担当者" as user
participant "SearchPurchaseHistoryController" as controller
participant "CustomerServide" as service1
participant "Order\nService" as service2
participant "Customer\nRepository" as repository1
participant "Order\nRepository" as repository2
database "db" as db
==表示==
user -> controller++:input()
controller -> service2++:selectPurchaseHistoryByPage(pageable:Pageable,date:LocalDateTime,customerId:Integer)
service2 -> repository2++:selectByPage(pageable:Pageable,date:LocalDateTime,customerId:Integer)
repository2 -> db++:SQL(SELECT(count))
db -> repository2--:List<Order>
repository2 -> service2--:List<Order>
service2 -> controller--:page<Order>

controller -> service1++:selectAll()
service1 -> repository1++:selectAll()
repository1 -> db++:SQL(SELECT)
db -> repository1--:List<ProductCategory>
repository1 -> service1--:List<ProductCategory>
service1 -> controller--:List<ProductCategory>
controller -> controller:Modelにセット\n(プルダウン用)
controller -> user--:カテゴリ別商品検索入力画面



@enduml